name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t my-app .

    - name: Run Syft for SBOM
      uses: anchore/sbom-action@v0.15.7
      with:
        image: "my-app:latest"
        output-file: "sbom.syft.json"

    - name: Run GitLeaks Secret Scan
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml # yoksa default config kullanır
        fail: false

    - name: Run Semgrep Security Scan
      run: |
        docker run --rm -v $(pwd):/src returntocorp/semgrep semgrep scan --config auto --sarif --output semgrep-results.sarif /src

    - name: Upload Semgrep SARIF
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sarif
        path: semgrep-results.sarif

    - name: Dummy Deploy Step
      run: |
        echo "Simulating deployment..."
        echo "Application deployed to http://localhost:8080 (dummy)"

    - name: Run OWASP ZAP DAST Scan
      run: |
        docker run -v $(pwd):/zap/wrk/:rw --network="host" ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8080 -g zap-report.md -r zap-report.html || true

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          zap-report.md
          zap-report.html

    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.syft.json
